### ISSUE TITLE
请问使用时需要将原有的WAN口删掉吗？

### ISSUE THREAD

**Issue by AnthonyMSen** [evindu/NetKeeper-Interception#2]
我在x86设备上使用esir编译的OpenWrt GDQ IPv4 v2020.06.01 | by "eSir PlayGround"固件，把WAN口删掉，只留下脚本创建的NETKEEPER接口，则可以正常使用。
请问这是推荐的操作吗？
设置后如下图：
![批注 2020-06-06 022536](https://user-images.githubusercontent.com/26853522/83910377-098a8b00-a79d-11ea-8794-22b60df802e4.png)

**Comment by eee-du** [comment]
默认会保留wan接口，保留wan口不影响正常上外网。
